In [ ]:
# importing a library
import numpy as np
import pandas as pd

In [ ]:
# Print function
print("Hello World")

# variables
name = "Hello"
number = 1
floatt = 3.5
print(number)

# Arithmatic operations
x = 2 # int
y = 3.4 # float

z = x + y
print(z)
print(type(z))

print(x * y)
print(x - y)
print(y ** x)

Hello World
1
5.4
<class 'float'>
6.8
-1.4
11.559999999999999


In [ ]:
# write a code to concat two strings
first_name = "Josh"
last_name = "Lawrence"

full_name = first_name + " " + last_name
print(full_name)

Josh Lawrence


**List**

In [ ]:
fruits = ["orange", "apple", "pearl", "banana"]
print(fruits)
print(fruits[1])

# remove an element
fruits.remove("apple")
print(fruits)
# fruits.remove("kiwi")

# add an item to list
fruits.append("blueberry")
print(fruits)

# count for an item
print(fruits.count("orange"))

# reverse a list
fruits.reverse()
print(fruits)

# sort a list
fruits.sort()
print(fruits)

print(dir(fruits))

['orange', 'apple', 'pearl', 'banana']
apple
['orange', 'pearl', 'banana']
['orange', 'pearl', 'banana', 'blueberry']
1
['blueberry', 'banana', 'pearl', 'orange']
['banana', 'blueberry', 'orange', 'pearl']
['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
list1 = [1 ,2, 3, 4, 5]
print(list1.pop())
print(list1)


5
[1, 2, 3, 4]


In [ ]:
# List comprehension
ls = []
for i in range(5):
    ls.append(i)
print(ls)

ls2 = [i for i in range(5)]
print(ls2)

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]


**Dictionary**

In [ ]:
distances = {"Toronto": 4095, "Hamilton": 4200, 2.2: 3000}
print(distances)

print(dir(distances))

print(distances["Toronto"])
# print(distances["Burlington"])
print(distances.get("Burlington"))
print(distances.get("Toronto"))

print(distances.keys())
print(distnaces.values())
print(distnaces.items())

print("--------")
for key, value in distnaces.items():
    print(key, value)

{'Toronto': 4095, 'Hamilton': 4200, 2.2: 3000}
['__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']
4095
None
4095
dict_keys(['Toronto', 'Hamilton', 2.2])
dict_values([4095, 4200, 3000])
dict_items([('Toronto', 4095), ('Hamilton', 4200), (2.2, 3000)])
--------
Toronto 4095
Hamilton 4200
2.2 3000


In [ ]:
dict1 = {}
for i in range(5):
    dict1[i] = str(i+1)
print(dict1)

dict2 = {i: str(i+1) for i in range(5)}
print(dict2)

{0: '1', 1: '2', 2: '3', 3: '4', 4: '5'}
{0: '1', 1: '2', 2: '3', 3: '4', 4: '5'}


**Numpy**

In [ ]:
import numpy as np

a = np.arange(15)
print(a)

b = a.reshape(5, 3)
print(b)

print(a.shape)
print(b.shape)

print(a.ndim)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
(15,)
(5, 3)
1
2


In [ ]:
A = np.zeros((3, 4))
print(A)

B = np.ones((3, 4))
print(B)

# Matrix addition
C = A + 2 * B
print(C)

print("--------")
# Matrix multiplication
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,1], [2,2], [3,3]])
print(A)
print(B)
print(np.dot(A, B))

print("--------")
# Transpose
AT = np.transpose(A)
print(AT)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
--------
[[1 2 3]
 [4 5 6]]
[[1 1]
 [2 2]
 [3 3]]
[[14 14]
 [32 32]]
--------
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
print(A)
C = A
print(C)

D = A.copy()
print(D)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


**Pandas**

In [ ]:
import pandas as pd
A = pd.Series([1, 3, 5, np.nan, 8])
print(A)

print("--------")
B = pd.date_range("20210921", periods=6)
print(B)
print(pd.Timestamp("20210921"))

0    1.0
1    3.0
2    5.0
3    NaN
4    8.0
dtype: float64
--------
DatetimeIndex(['2021-09-21', '2021-09-22', '2021-09-23', '2021-09-24',
               '2021-09-25', '2021-09-26'],
              dtype='datetime64[ns]', freq='D')
2021-09-21 00:00:00


In [ ]:
df = pd.DataFrame({
    "sr_no": range(4),
    "date_time": pd.Timestamp("20210921"),
    "value": pd.Series(1, index=list(range(4)), dtype="float32")
})
print(df)

   sr_no  date_time  value
0      0 2021-09-21    1.0
1      1 2021-09-21    1.0
2      2 2021-09-21    1.0
3      3 2021-09-21    1.0


**Function**

In [ ]:
def print_string(str):
    print(str)
print_string("Hello")

# lmabda/anonymous function
compute = lambda x, y: x ** 5 + y ** 2
print(compute(2, 3))

def compute2(x , y):
    return x ** 5 + y ** 2
print(compute2(2, 3))

Hello
41
41


**Class**

In [ ]:
class Students:
    program = "B.Tech"
    def __init__(self, name, student_no, year):
        self.name = name
        self.student_no = student_no
        self.year = year

s1 = Students('4AI3', 123, 2021)
print(s1.name)
print(s1.year)
print(s1.program)

4AI3
2021
B.Tech
